In [2]:
# openCV는 자료구조로 numpy를 사용한다.
import cv2

In [3]:
img = cv2.imread('images/read_color.jpg')
print(type(img))

<class 'numpy.ndarray'>


In [7]:
print(img.ndim) # 차원의 수
print(img.shape) # 각 차원의 크기(튜플)
print(img.size) # 전체 이미지의 크기(bytes)
print(img.dtype) # 요소의 데이터의 타입
print(img.itemsize) # 각 요소의 바이트 크기

3
(300, 400, 3)
360000
uint8
1


In [5]:
import numpy as np  # Numpy를 사용할 때 통상적으로 이렇게 np로 줄여서 사용한다.
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
a.dtype

dtype('int64')

In [12]:
a = np.array([1, 2, 3.14, 4])
a

array([1.  , 2.  , 3.14, 4.  ])

In [14]:
a.shape # 1행 4열

(4,)

In [15]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b.shape # 2행 4열

(2, 4)

In [18]:
c = np.array([[1], [2], [3], [4]])
c

array([[1],
       [2],
       [3],
       [4]])

In [19]:
c.shape # 4행 1열

(4, 1)

In [26]:
d = np.array([[1, 2, 3, 4]])
d

array([[1, 2, 3, 4]])

In [27]:
d.T # 전치행렬

array([[1],
       [2],
       [3],
       [4]])

In [3]:
a = np.empty((2,3)) # 환경에 따라서 0으로 채워지기도 하지만, prompt 상에서 실행
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
a.dtype

dtype('float64')

In [6]:
a.fill(255) # 주어진 값으로 채움
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [7]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.zeros((2, 3), dtype=np.uint8) # 이미지의 픽셀은 정수값을 사용하므로 8비트
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [9]:
d = np.ones((2, 3), dtype=np.int16)
d

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [10]:
e = np.full((2, 4, 3), 255, dtype=np.uint8) # 컬러 이미지는 하나의 픽셀이 RGB값을 값으로 3개의 채널을 가짐
e

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [3]:
import cv2
img = cv2.imread('images/read_color.jpg')
img

array([[[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       ...,

       [[ 51,  64,  56],
        [ 51,  64,  56],
        [ 42,  55,  47],
        ...,
        [145, 149, 150],
        [162, 166, 167],
        [161, 165, 166]],

       [[ 31,  50,  41],
        [ 35,  56,  47],
        [ 28,  53,  43],
        ...,
        [152, 155, 159],
        [163, 166, 170],
        [155, 158, 162]],

       [[ 22,  46,  36],
        [ 16,  43,  33],
        [ 19,  51,  40],
        ...,
        [151, 154, 159],
        [147, 150, 155],
        [157, 160, 165]]

In [6]:
a = np.empty_like(img) # 배열의 크기만 같고 내용은 무작위로 들어간다.
a

array([[[ 80,   1,  94],
        [107, 129,   1],
        [  0,   0,  32],
        ...,
        [255, 255, 255],
        [255, 255,  26],
        [  1, 255, 255]],

       [[255, 255,  91],
        [  0, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [  9,   3, 255],
        ...,
        [  4, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[159, 155, 160],
        [159, 161, 166],
        [165, 146, 151],
        ...,
        [150, 157, 161],
        [162, 155, 159],
        [160, 157, 161]],

       [[162, 159, 163],
        [164, 148, 152],
        [153, 145, 149],
        ...,
        [164, 165, 168],
        [172, 152, 155],
        [159, 151, 154]],

       [[158, 137, 140],
        [144, 155, 158],
        [162, 152, 155],
        ...,
        [154, 137, 140],
        [145, 156, 159],
        [164, 163, 166]]

In [7]:
b = np.zeros_like(img)
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(300, 400, 3), dtype=uint8)

In [8]:
print(img.shape)
print(a.shape)
print(b.shape)

(300, 400, 3)
(300, 400, 3)
(300, 400, 3)


In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [27]:
c = np.arange(3, 9, 2) # 시작, 끝, 증분
c

array([3, 5, 7])

In [28]:
d = np.random.rand(2, 3) # 0~1 사이값으로 2행3열
d

array([[0.85480421, 0.67942482, 0.33203026],
       [0.8626313 , 0.87835016, 0.49607548]])

In [9]:
e = np.random.randn(2, 3) # 표준정규분포(평균:0, 분산:1)를 따르는 난수로 2행 3열
e

array([[-0.24879593,  1.33197145, -0.68176826],
       [-1.06750788, -1.19744927, -1.35297928]])

In [31]:
f = np.random.randint(0, 256, (3, 3)) # 시작, 끝, 3행3열 정수값
f

array([[ 80,  81, 137],
       [216, 187,   7],
       [100,  78,  39]], dtype=int32)

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
b = a.astype(np.float64) # 자료형의 스트링을 써도 된다. 
b

array([0., 1., 2., 3., 4.])

In [36]:
c = np.uint8(a) # dtype 함수를 사용할 수도 있다.
c

array([0, 1, 2, 3, 4], dtype=uint8)

In [38]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [39]:
b = a.reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
c = np.reshape(a, (2, 3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
d = np.arange(100).reshape(2, -1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [42]:
e = np.arange(100).reshape(-1, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [44]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
b = a.reshape((6,))
b

array([0., 0., 0., 0., 0., 0.])

In [47]:
c = a.reshape(-1)
c

array([0., 0., 0., 0., 0., 0.])

In [48]:
d = np.ravel(a)
d

array([0., 0., 0., 0., 0., 0.])

In [49]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
b = a.T
b

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [10]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [53]:
a + 5

array([5, 6, 7, 8, 9])

In [54]:
a - 2

array([-2, -1,  0,  1,  2])

In [55]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [56]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [58]:
a > 2

array([False, False, False,  True,  True])

In [59]:
a = np.arange(24).reshape(2, 3, 4)
b = np.arange(12).reshape(3, 4)
print(a)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
a + b

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [11]:
c = np.arange(3).reshape(3, 1)
c

array([[0],
       [1],
       [2]])

In [16]:
d = np.arange(6).reshape(2,3,1)
d

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [17]:
e = np.arange(6).reshape(2, 3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
f = np.arange(6).reshape(3, 2)
f

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
d + f

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 3,  4],
        [ 6,  7],
        [ 9, 10]]])

# 2.6 인덱싱과 슬라이싱

In [23]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a[1] # 인덱싱

array([4, 5, 6, 7])

In [25]:
a[2, 3] # 비교) python list의 인덱싱: a[2][3[

np.int64(11)

In [26]:
b = a[0:2, 1:3] # 슬라이싱
b

array([[1, 2],
       [5, 6]])

In [27]:
b[0] = 99
b

array([[99, 99],
       [ 5,  6]])

In [28]:
a # 슬라이싱은 원본의 참조이므로 값을 변경하면 원본도 변경된다.

array([[ 0, 99, 99,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 비교: 파이썬 리스트의 슬라이싱

In [29]:
la = [1, 2, 3, 4]
lb = la[1:3]
lb

[2, 3]

In [30]:
lb[0] = 100
lb

[100, 3]

In [31]:
a = np.arange(12).reshape(3, 4)

In [32]:
c = a[0:2, 1:3].copy() # 원본을 바꾸지 않으려면 복사를 해야 한다.
c

array([[1, 2],
       [5, 6]])

In [34]:
c[0] = 99
c

array([[99, 99],
       [ 5,  6]])

In [35]:
a # 원본이 바뀌지 않음

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 2.7 펜시 인덱싱

In [36]:
a = np.arage(3, 8)
a

array([3, 4, 5, 6, 7])

In [37]:
a[[1, 3, 4]]

array([4, 6, 7])

In [39]:
b = [1, 2, 3]
a[b] # 리스트형 변수를 사용해도 된다.

array([4, 5, 6])

In [40]:
a[[True, False, True, False, True]] # bool인 경우에는 배열의 크기와 같아야 한다.

array([3, 5, 7])

In [41]:
a = np.arange(10)
b = a > 5
b

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [42]:
a[b]

array([6, 7, 8, 9])

In [44]:
a[a>5]

array([6, 7, 8, 9])

In [45]:
a[a>5] = 1
a

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1])

In [46]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [47]:
a[[3], [5]]

array([23])

In [48]:
a[[0, 2], [2, 3]]

array([ 2, 15])

In [51]:
b = np.arange(30).reshape(2, 5, 3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [52]:
b[[0,1],[2,3],[1,2]]

array([ 7, 26])

In [63]:
b[[0,1,0,0,1], np.arange(5), np.random.randint(0,3,(5,))]

array([ 0, 19,  6, 10, 28])

# 2.8 병합과 분리

In [64]:
import numpy as np
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [65]:
b = np.arange(10, 14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [66]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [67]:
np.hstack((a, b))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [68]:
e = np.hstack((a, b))
e.shape

(2, 4)

In [69]:
f = np.vstack((a,b))
f.shape

(4, 2)

In [70]:
np.concatenate((a,b),0)

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [71]:
np.concatenate((a,b),1)

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [72]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
np.vsplit(b,2)

[array([[10, 11]]), array([[12, 13]])]

In [74]:
np.split(b,2,0) # 0번 축은 y축, 즉 vsplit()과 같다.

[array([[10, 11]]), array([[12, 13]])]

In [75]:
np.vsplit(b, [1])

[array([[10, 11]]), array([[12, 13]])]

In [76]:
np.hsplit(b, [1])

[array([[10],
        [12]]),
 array([[11],
        [13]])]

In [77]:
np.split(b,[1], 1) # 1번 축은 x축, 즉, hsplit()과 같다.

[array([[10],
        [12]]),
 array([[11],
        [13]])]

# 2.9 검색 기능

In [78]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
coords = np.where(a>6)
coords

(array([1, 2, 2, 2, 2]), array([3, 0, 1, 2, 3]))

In [80]:
np.stack((coords[0], coords[1]), -1) # 좌표로 사용하려면 stack()함수를 사용

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]])

In [81]:
b = np.array([0, 1, 2, 0, 1, 2])
np.nonzero(b) # 1차원 배열인 경우, 인덱스들의 배열을 리턴함.

(array([1, 2, 4, 5]),)

In [83]:
c = np.array([[0,1,2], [1,2,0], [2,0,1]])
c

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [84]:
coords = np.nonzero(c) # 다차원배열인 경우에는 각 축의 인덱스값의 배열들을 리턴
coords

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 1, 0, 2]))

In [85]:
np.stack((coords[0], coords[1]), -1) # stack() 함수를 써서 병합

array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])

In [86]:
d = np.array([[[True, False, True, True], [True, True, False, True], [True, True, True,    True]],    [[True,    True,    True,    True],    [True, 
False,    True,    True],    [True,    True,    True,    True]]])

In [87]:
d.shape

(2, 3, 4)

In [89]:
np.all(d,1)

array([[ True, False, False,  True],
       [ True, False,  True,  True]])

In [90]:
np.all(d,2)

array([[False, False,  True],
       [ True, False,  True]])

In [91]:
a = np.arange(10)
b = np.arange(10)
a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [93]:
np.all(a==b)

np.True_

In [94]:
b[5] = -1 # b 배열의 요소 하나를 변경하고 
b

array([ 0,  1,  2,  3,  4, -1,  6,  7,  8,  9])

In [95]:
np.all(a==b)  # a 배열과 비교하면 서로 다르므로 all()의 결과는 False

np.False_

In [96]:
np.any(d) # d 배열 요소 중에서 True가 하나 이상 있으면 True

np.True_

In [97]:
np.any(d,1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# 2.10 기초 통계함수

In [99]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
np.sum(a)

np.int64(66)

In [102]:
np.sum(a,0)

array([12, 15, 18, 21])

In [104]:
np.sum(a,1)

array([ 6, 22, 38])

In [105]:
np.mean(a)

np.float64(5.5)

In [106]:
np.mean(a, 0)

array([4., 5., 6., 7.])

In [107]:
np.mean(a, 1)

array([1.5, 5.5, 9.5])

In [108]:
np.amin(a)

np.int64(0)

In [109]:
np.amin(a,0)

array([0, 1, 2, 3])

In [110]:
np.amin(a, 1)

array([0, 4, 8])

In [111]:
np.amax(a)

np.int64(11)

In [112]:
np.amax(a,0)

array([ 8,  9, 10, 11])

In [113]:
np.amax(a, 1)

array([ 3,  7, 11])