In [2]:
# openCV는 자료구조로 numpy를 사용한다.
import cv2

In [3]:
img = cv2.imread('images/read_color.jpg')
print(type(img))

<class 'numpy.ndarray'>


In [7]:
print(img.ndim) # 차원의 수
print(img.shape) # 각 차원의 크기(튜플)
print(img.size) # 전체 이미지의 크기(bytes)
print(img.dtype) # 요소의 데이터의 타입
print(img.itemsize) # 각 요소의 바이트 크기

3
(300, 400, 3)
360000
uint8
1


In [2]:
import numpy as np  # Numpy를 사용할 때 통상적으로 이렇게 np로 줄여서 사용한다.
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
a.dtype

dtype('int64')

In [12]:
a = np.array([1, 2, 3.14, 4])
a

array([1.  , 2.  , 3.14, 4.  ])

In [14]:
a.shape # 1행 4열

(4,)

In [15]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b.shape # 2행 4열

(2, 4)

In [18]:
c = np.array([[1], [2], [3], [4]])
c

array([[1],
       [2],
       [3],
       [4]])

In [19]:
c.shape # 4행 1열

(4, 1)

In [26]:
d = np.array([[1, 2, 3, 4]])
d

array([[1, 2, 3, 4]])

In [27]:
d.T # 전치행렬

array([[1],
       [2],
       [3],
       [4]])

In [3]:
a = np.empty((2,3)) # 환경에 따라서 0으로 채워지기도 하지만, prompt 상에서 실행
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
a.dtype

dtype('float64')

In [6]:
a.fill(255) # 주어진 값으로 채움
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [7]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
c = np.zeros((2, 3), dtype=np.uint8) # 이미지의 픽셀은 정수값을 사용하므로 8비트
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [9]:
d = np.ones((2, 3), dtype=np.int16)
d

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [10]:
e = np.full((2, 4, 3), 255, dtype=np.uint8) # 컬러 이미지는 하나의 픽셀이 RGB값을 값으로 3개의 채널을 가짐
e

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [19]:
import cv2
img = cv2.imread('images/read_color.jpg')
img

array([[[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       ...,

       [[ 51,  64,  56],
        [ 51,  64,  56],
        [ 42,  55,  47],
        ...,
        [145, 149, 150],
        [162, 166, 167],
        [161, 165, 166]],

       [[ 31,  50,  41],
        [ 35,  56,  47],
        [ 28,  53,  43],
        ...,
        [152, 155, 159],
        [163, 166, 170],
        [155, 158, 162]],

       [[ 22,  46,  36],
        [ 16,  43,  33],
        [ 19,  51,  40],
        ...,
        [151, 154, 159],
        [147, 150, 155],
        [157, 160, 165]]

In [20]:
a = np.empty_like(img) # 배열의 크기만 같고 내용은 무작위로 들어간다.
a

array([[[ 80,   1, 151],
        [ 63, 211,   1],
        [  0,   0, 240],
        ...,
        [ 55,  49,  44],
        [ 50,  55,  50],
        [ 44,  51,  48]],

       [[ 53,  44,  51],
        [ 49,  53,  44],
        [ 51,  51,  52],
        ...,
        [ 34,  32, 112],
        [104, 111, 116],
        [111, 115, 104]],

       [[111, 112,  58],
        [ 73,  67,  67],
        [ 80, 114, 111],
        ...,
        [ 32,  32,  32],
        [ 32,  32,  32],
        [ 32,  32,  32]],

       ...,

       [[ 20,  12,  18],
        [ 16,   8,  25],
        [ 23,  15,  15],
        ...,
        [ 32,  23,  35],
        [ 30,  21,  24],
        [ 21,  13,  16]],

       [[ 14,   6,  13],
        [ 14,   5,  36],
        [ 37,  28,  53],
        ...,
        [ 26,  20,  55],
        [ 41,  35,  45],
        [ 34,  26,  39]],

       [[ 29,  19,  33],
        [ 23,  13,  42],
        [ 32,  22,  67],
        ...,
        [ 27,  21,  45],
        [ 34,  26,  52],
        [ 41,  33,  52]]

In [21]:
b = np.zeros_like(img)
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(300, 400, 3), dtype=uint8)

In [22]:
print(img.shape)
print(a.shape)
print(b.shape)

(300, 400, 3)
(300, 400, 3)
(300, 400, 3)


In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [27]:
c = np.arange(3, 9, 2) # 시작, 끝, 증분
c

array([3, 5, 7])

In [28]:
d = np.random.rand(2, 3) # 0~1 사이값으로 2행3열
d

array([[0.85480421, 0.67942482, 0.33203026],
       [0.8626313 , 0.87835016, 0.49607548]])

In [30]:
e = np.random.randn(2, 3) # 표준정규분포(평균:0, 분산:1)를 따르는 난수로 2행 3열
e

array([[ 0.00584276,  0.36621257,  0.99781755],
       [-0.42600668, -0.19178275, -0.50830867]])

In [31]:
f = np.random.randint(0, 256, (3, 3)) # 시작, 끝, 3행3열 정수값
f

array([[ 80,  81, 137],
       [216, 187,   7],
       [100,  78,  39]], dtype=int32)

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
b = a.astype(np.float64) # 자료형의 스트링을 써도 된다. 
b

array([0., 1., 2., 3., 4.])

In [36]:
c = np.uint8(a) # dtype 함수를 사용할 수도 있다.
c

array([0, 1, 2, 3, 4], dtype=uint8)

In [38]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [39]:
b = a.reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
c = np.reshape(a, (2, 3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
d = np.arange(100).reshape(2, -1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [42]:
e = np.arange(100).reshape(-1, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [44]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
b = a.reshape((6,))
b

array([0., 0., 0., 0., 0., 0.])

In [47]:
c = a.reshape(-1)
c

array([0., 0., 0., 0., 0., 0.])

In [48]:
d = np.ravel(a)
d

array([0., 0., 0., 0., 0., 0.])

In [49]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
b = a.T
b

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [52]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [53]:
a + 5

array([5, 6, 7, 8, 9])

In [54]:
a - 2

array([-2, -1,  0,  1,  2])

In [55]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [56]:
b = np.arange(6).reshape(2, -1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [58]:
a > 2

array([False, False, False,  True,  True])

In [59]:
a = np.arange(24).reshape(2, 3, 4)
b = np.arange(12).reshape(3, 4)
print(a)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
a + b

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [62]:
c = np.arange(3).reshape(3, 1)
c

array([[0],
       [1],
       [2]])